import type { ThingToDo } from '../../core/models/types';
const cardImage = {id:'don-det-river-card',src:'/media/don-det/river.svg',alt:'Mekong river landscape near Don Det',sourceType:'manual' as const,sourceName:'Things To Do Atlas V2',manual:true,locked:true};
const media = {hero:{stamps:[],drawings:[],photos:[]},card:{image:cardImage},fieldCard:{gallery:[]}};
const compact = {template:'compact' as const,whyGo:'A powerful river landscape within easy reach of Don Det.',practical:'Bring water, sun protection and cash for local transport or entry points.',access:'Use a bicycle, boat or tuk-tuk arrangement from Don Det depending on the season.',notes:'Paths and viewpoints can be uneven after rain.',faq:[{question:'Is this a full-day trip?',answer:'Plan a relaxed half-day and allow time for boats or cycling.'}]};
export const donDetThings: ThingToDo[] = [
{id:'thing-li-phi-falls',slug:'li-phi-falls',name:'Li Phi Falls',country:'laos',city:'don-det',category:'things-to-do',coordinates:{latitude:13.946,longitude:105.882},googleMapsUrl:'https://www.google.com/maps/search/?api=1&query=Li+Phi+Falls+Laos',shortDescription:'A Mekong waterfall complex near Don Det.',longDescription:'Li Phi Falls is a core Don Det landmark and validates the single Thing To Do entity across editorial and planning surfaces.',isLandmark:true,media,isMySelection:true,selectionRank:1,sourceMetadata:{sourceName:'Editorial seed'},manualLocks:{},breadcrumbs:['Laos','Don Det','Things to do'],fieldCard:{...compact,template:'deep',whyGo:'The falls express the scale and force of the Mekong at the southern islands.',sections:[{title:'What to expect',body:'Fast water, rocky channels and a landscape that rewards an unhurried visit.'},{title:'Context',body:'This is one of the natural reference points for the Four Thousand Islands.'}]}},
{id:'thing-old-french-railway-bridge',slug:'old-french-railway-bridge',name:'Old French railway bridge',country:'laos',city:'don-det',category:'things-to-do',coordinates:{latitude:13.947,longitude:105.921},googleMapsUrl:'https://www.google.com/maps/search/?api=1&query=Old+French+Railway+Bridge+Don+Khon',shortDescription:'A historic crossing on the route between Don Det and Don Khon.',longDescription:'A landmark stop on the island route, represented once as a Thing To Do.',isLandmark:true,media,isMySelection:false,sourceMetadata:{sourceName:'Editorial seed'},manualLocks:{},breadcrumbs:['Laos','Don Det','Things to do'],fieldCard:{...compact,whyGo:'It adds a human and historical layer to a day of river landscapes.'}},
{id:'thing-irrawaddy-dolphin-viewpoint',slug:'irrawaddy-dolphin-viewpoint',name:'Irrawaddy dolphin viewpoint',country:'laos',city:'don-det',category:'things-to-do',coordinates:{latitude:13.927,longitude:105.880},googleMapsUrl:'https://www.google.com/maps/search/?api=1&query=Irrawaddy+Dolphin+Viewpoint+Don+Khon',shortDescription:'A river viewpoint associated with the rare Irrawaddy dolphin habitat.',longDescription:'A nature-focused landmark in the southern island landscape.',isLandmark:true,media,isMySelection:false,sourceMetadata:{sourceName:'Editorial seed'},manualLocks:{},breadcrumbs:['Laos','Don Det','Things to do'],fieldCard:{...compact,whyGo:'It connects a quiet river stop with one of the region’s most distinctive wildlife stories.'}},
{id:'thing-don-det-cycle-loop',slug:'don-det-cycle-loop',name:'Don Det cycle loop',country:'laos',city:'don-det',category:'things-to-do',coordinates:{latitude:13.956,longitude:105.923},shortDescription:'A self-guided ride around the island.',longDescription:'A deliberately simple activity record proving that not every Thing To Do is a landmark.',isLandmark:false,media,isMySelection:false,sourceMetadata:{sourceName:'Editorial seed'},manualLocks:{},breadcrumbs:['Laos','Don Det','Things to do'],fieldCard:{...compact,whyGo:'Cycling is the simplest way to understand the island’s scale and pace.'}}];
