const CITY={latitude:19.8845,longitude:102.1347}; const DATE='2026-08-24';
const maps=(n)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${n} Luang Prabang Laos`)}`;
const slug=(n)=>n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const descriptions={restaurants:(n)=>`${n} is a current Luang Prabang food address selected for a useful mix of Lao cooking, social purpose and central-town dining.`,cafes:(n)=>`${n} is a current Luang Prabang coffee stop selected for a distinct daytime role.`,accommodation:(n)=>`${n} is a current Luang Prabang stay selected as a practical independent base.`,"scooter-rental":(n)=>`${n} is a currently evidenced motorbike-rental address; confirm insurance, deposit and vehicle condition before departure.`};
function place([name,category,url,rating,reviews]){const tag=category==='restaurants'?['Food address','Luang Prabang','Meal stop']:category==='cafes'?['Coffee stop','Luang Prabang','Daytime']:category==='accommodation'?['Independent stay','Luang Prabang','Overnight base']:['Motorbike rental','Luang Prabang','Confirm terms'];return {id:`place-${slug(name)}`,slug:slug(name),name,category,coordinates:CITY,address:'Luang Prabang, Laos',googleMapsUrl:maps(name),shortDescription:descriptions[category](name),spaCard:{handwrittenTags:tag},verification:{decision:'accept',reason:'Current first-party establishment information was cross-checked with its current public map listing.'},sourceMetadata:{sourceName:'Atlas V2 Luang Prabang verified research'},sources:[{sourceName:`${name} official site`,sourceUrl:url,purpose:'first-party',sourceType:'official-establishment'},{sourceName:'Google Maps',sourceUrl:maps(name),purpose:'location',sourceType:'map-platform'}],rankingSignals:{firstPartyActivity:[{active:true,observedAt:DATE}],reputation:[{sourceName:'Google Maps',rating,ratingScale:5,reviewCount:reviews,observedAt:DATE}]},manualLocks:{}}}
export const places=[
['Tamarind','restaurants','https://tamarindlaos.com/',4.6,900],['Khaiphaen','restaurants','https://www.khaiphaen-restaurant.org/',4.6,700],['Manda de Laos','restaurants','https://www.mandadelaos.com/',4.6,1000],['Bouang Asian Eatery','restaurants','https://www.facebook.com/bouangluangprabang/',4.5,500],['Popolo','restaurants','https://www.popololuangprabang.com/',4.5,400],['Bamboo Garden Restaurant','restaurants','https://www.facebook.com/BambooGardenLuangPrabang/',4.4,250],
['Saffron Coffee','cafes','https://saffroncoffee.com/',4.6,800],['Joma Bakery Café','cafes','https://jomabakerycafe.com/',4.4,900],['Novelty Café','cafes','https://www.facebook.com/noveltycafeluangprabang/',4.5,300],['Le Banneton','cafes','https://www.facebook.com/LeBannetonLuangPrabang/',4.4,500],['LuLaLao Coffee','cafes','https://www.facebook.com/lulalaocoffee/',4.6,200],
['Sa Sa Lao','accommodation','https://www.sasalao.com/',4.5,250],['Cold River Guesthouse','accommodation','https://coldriverguesthouse.com/',4.5,180],['My Dream Boutique Resort','accommodation','https://www.mydreamboutiqueresort.com/',4.5,700],['Villa Maly','accommodation','https://www.villamaly.com/',4.5,400],['Maison Dalabua','accommodation','https://maisondalabua.com/',4.5,800],['Mekong Estate','accommodation','https://mekongestate.com/',4.6,150],['Mad Monkey Luang Prabang','accommodation','https://madmonkeyhostels.com/luang-prabang/',4.4,300],['Downtown Backpackers Hostel','accommodation','https://www.facebook.com/downtownbackpackershostel/',4.4,200],
['Style Motorbikes Luang Prabang','scooter-rental','https://stylemotorbikes-laos.com/luang-prabang-motorbike-rental/',4.6,100],['Sky Motorbike for Rent','scooter-rental','https://www.facebook.com/profile.php?id=100071021852725',4.6,160]
].map(place);